---
# Ρυθμίσεις για τον Skroutz Crawler
crawler:
  # skroutz_cookie: <YOUR SKROUTZ COOKIE HERE>
# Λίστα με parsers συσκεκριμένων καταστημάτων
shop_parsers:
  - 1283
  - 3292
# Λίστα με φίλτρα για πρόσθετο καθάρισμα, φορμάρισμα τιμών
filters:
  - AirconditionSpecsNormalizer
# Ρυθμίσεις για φορμάρισμα της έξοδου
export:
  csv:
    # Να συμπεριληφθούν όλα τα πεδία τιμών που βρέθηκαν. Καθορίστε το ως false
    # αν θέλετε το csv να περιέχει μόνο τα πεδία που ορίζονται στη λίστα headers
    include_all_headers: true
    # Λίστα με τα πεδία που θα συμπεριληφθούν, καθώς και η σειρά που θα εμφανίζονται 
    headers:
      - Brand
      - Product
      - Τιμή
      - Καλύπτει χώρους (m²)
      - Βαθμός Απόδοσης Ψύξης (SEER)
      - Ισχύς Ψύξης
      - Κατανάλωση Ψύξης
      - Ελάχιστη Ψύξη (Btu/h)
      - Μέγιστη Ψύξη (Btu/h)
      - Βαθμός Απόδοσης Θέρμανσης (SCOP)
      - Ισχύς Θέρμανσης
      - Κατανάλωση Θέρμανσης
      - Ελάχιστη Θέρμανση (Btu/h)
      - Μέγιστη Θέρμανση (Btu/h)
      - Βαθμολογία
      - Αξιολογήσεις
      - WiFi
      - Ιονιστής